version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo "Current directory: $(pwd)"
      - echo "Listing contents:"
      - ls -la
      - npm install
  build:
    commands:
      - echo "Running build phase..."
      - npm run build || echo "No build script found"

artifacts:
  files:
    - '**/*'
