version: 0.2

phases:
  install:
    commands:
      - echo "Installing dependencies..."
      - cd src || true
      - npm install
  build:
    commands:
      - echo "Building application..."
      - npm run build || echo "No build script found"
artifacts:
  files:
    - '**/*'
